export { device } from "./device";
export { default as allEqual } from "./allEqual";
export { default as addZeroNumber } from "./addZeroNumber";
export { default as capitalize } from "./capitalize";
export { default as checkResponsibleAge } from "./checkResponsibleAge";
export { default as compareObjects } from "./compareObjects";
export { default as formatCellphone } from "./formatCellphone";
export { default as formatCEP } from "./formatCEP";
export { default as formatCPF } from "./formatCPF";
export { default as formatCNPJ } from "./formatCNPJ";
export { default as PhoneParts } from "./PhoneParts";
export { RE_DIGIT, RE_NODIGIT } from "./regex";
export { default as removeCharSpecial } from "./removeCharSpecial";
export { default as removeMask } from "./removeMask";
export { default as splitDate } from "./splitDate";
export { default as splitMask } from "./splitMask";
export { default as validateAddressNumber } from "./validateAddressNumber";
export { default as validateCEP } from "./validateCEP";
export { default as validateCPF } from "./validateCPF";
export { default as validateCNPJ } from "./validateCNPJ";
export { default as validatePhone } from "./validatePhone";
export { default as verifyMobile } from "./verifyMobile";
export { default as getTimeQueue } from "./getTimeQueue";
